
logging.level:
  org.springframework.*: debug

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /mail

    binding:
      mail:
        queue: mail.queue
        exchange: mail.direct
        rountingKey: mail.queue