server.port: 8180

logging.level:
  org.springframework.boot: debug

spring.profiles.active: develop

spring:
  profiles: develop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true