server:
  port: 8083
  context-path: /api/v1

logging.level:
  org.springframework.*: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/shooter9;Mode=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect